version: '3.9'
services:
  builder:
    build: ./docker/builder
    volumes:
    - ./:/host
  stolon:
    build: ./docker/stolon
    environment:
      CLUSTER_SIZE: 3
    ports:
    - "25432"
    - "5432"
    - "2345"
    volumes:
    - ./:/host
