name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: install compose
        run: |
          docker-compose --version
          echo $PGVERSION
      - name: start compose env
        run: |
          docker-compose up -d --scale stolon=3
      - name: build binaries
        run: |
          docker-compose exec builder /bin/bash -ic 'cd /host && make build_dlv build_pgquartz'
      - name: run binaries
        run: |
          for ((i=1;i<=3;i++)); do
            echo "pgquartz-stolon-${i}"
            docker exec "pgquartz-stolon-${i}" bash -c '/host/bin/pgquartz.$(uname -m) -c /host/jobs/jobspec1/job.yml' &
            sleep 1
          done
